# Generated by Django 6.1 on 2026-08-27 22:25

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='الصورة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'من نحن',
                'verbose_name_plural': 'من نحن',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
            ],
            options={
                'verbose_name': 'رسالة اتصال',
                'verbose_name_plural': 'رسائل الاتصال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(help_text='الصورة التي تظهر في الصفحة الرئيسية', upload_to='services/thumbnails/', verbose_name='الصورة المصغرة')),
                ('main_image', models.ImageField(help_text='الصورة التي تظهر في صفحة الخدمة', upload_to='services/main/', verbose_name='الصورة الرئيسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('order', models.IntegerField(default=0, help_text='رقم الترتيب (الأصغر يظهر أولاً)', verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['order', 'id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(default='من نحن', max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(help_text='محتوى صفحة من نحن (يمكن استخدام HTML)', verbose_name='المحتوى')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='omarusaapp.about')),
            ],
            options={
                'verbose_name': 'من نحن Translation',
                'db_table': 'omarusaapp_about_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='omarusaapp_about_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('slug', models.SlugField(help_text='الرابط الذي سيظهر في المتصفح', max_length=200, unique=True, verbose_name='الرابط')),
                ('short_description', models.TextField(help_text='يظهر في البطاقة في الصفحة الرئيسية', max_length=500, verbose_name='وصف قصير')),
                ('full_description', models.TextField(help_text='يظهر في صفحة الخدمة', verbose_name='وصف كامل')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='omarusaapp.service')),
            ],
            options={
                'verbose_name': 'خدمة Translation',
                'db_table': 'omarusaapp_service_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='omarusaapp_service_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
