# Generated by Django 6.1 on 2026-08-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttranslation',
            name='content',
            field=models.TextField(blank=True, help_text='محتوى صفحة من نحن (يمكن استخدام HTML)', verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, help_text='الصورة التي تظهر في صفحة الخدمة', null=True, upload_to='services/main/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='الصورة التي تظهر في الصفحة الرئيسية', null=True, upload_to='services/thumbnails/', verbose_name='الصورة المصغرة'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='full_description',
            field=models.TextField(blank=True, help_text='يظهر في صفحة الخدمة', verbose_name='وصف كامل'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='short_description',
            field=models.TextField(blank=True, help_text='يظهر في البطاقة في الصفحة الرئيسية', max_length=500, verbose_name='وصف قصير'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='slug',
            field=models.SlugField(blank=True, help_text='الرابط الذي سيظهر في المتصفح', max_length=200, null=True, unique=True, verbose_name='الرابط'),
        ),
    ]
