# Generated by Django 6.1 on 2026-08-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0002_alter_abouttranslation_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='الرابط'),
        ),
    ]
