# Generated by Django 6.1 on 2026-08-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0003_alter_servicetranslation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetranslation',
            name='slug',
            field=models.SlugField(blank=True, help_text='اتركه فارغاً وسيتولد تلقائياً', max_length=200, null=True, unique=True, verbose_name='الرابط (اختياري)'),
        ),
    ]
