# Generated by Django 6.1 on 2026-08-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0004_alter_servicetranslation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttranslation',
            name='content',
            field=models.TextField(blank=True, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/main/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='services/thumbnails/', verbose_name='الصورة المصغرة'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='وصف كامل'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='وصف قصير'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='الرابط'),
        ),
    ]
