# Generated by Django 6.1 on 2026-08-28 03:40

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0006_alter_about_image_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='رابط انستغرام')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='رابط تويتر')),
            ],
            options={
                'verbose_name': 'إعداد الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettingTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('copyright_text', models.CharField(default='© Clear Document Preparation LLC. All rights reserved', max_length=255, verbose_name='نص حقوق النشر')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='omarusaapp.sitesetting')),
            ],
            options={
                'verbose_name': 'إعداد الموقع Translation',
                'db_table': 'omarusaapp_sitesetting_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='omarusaapp_sitesetting_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
