# Generated by Django 6.1 on 2026-08-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0007_sitesetting_sitesettingtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='شعار الشركة'),
        ),
        migrations.AddField(
            model_name='sitesettingtranslation',
            name='company_name',
            field=models.CharField(default='Clear Document Preparation LLC', max_length=200, verbose_name='اسم الشركة'),
        ),
        migrations.AddField(
            model_name='sitesettingtranslation',
            name='welcome_text',
            field=models.TextField(blank=True, null=True, verbose_name='النص الترحيبي (الصفحة الرئيسية)'),
        ),
    ]
