# Generated by Django 6.1 on 2026-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0008_sitesetting_logo_sitesettingtranslation_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='admin_receive_email',
            field=models.EmailField(blank=True, help_text='البريد الذي ستصلك إليه رسائل العملاء', max_length=254, null=True, verbose_name='بريد استقبال الرسائل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host',
            field=models.CharField(blank=True, help_text='مثال: mail.yourdomain.com', max_length=255, null=True, verbose_name='خادم البريد (SMTP Host)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='كلمة مرور البريد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بريد المرسل (Email User)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_port',
            field=models.IntegerField(default=465, help_text='غالباً 465 لـ SSL أو 587 لـ TLS', verbose_name='بورت البريد (Port)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_use_ssl',
            field=models.BooleanField(default=True, verbose_name='استخدام SSL (للبورت 465)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني المعروض بالفوتر'),
        ),
    ]
