# Generated by Django 6.1 on 2026-08-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0009_sitesetting_admin_receive_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='اتركه فارغاً لإخفاء الأيقونة. مثال للصيغة: 193318181', max_length=20, null=True, verbose_name='رقم واتساب (مع رمز الدولة)'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email_host',
            field=models.CharField(blank=True, help_text='مثال: smtp-relay.brevo.com', max_length=255, null=True, verbose_name='خادم البريد (SMTP Host)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email_port',
            field=models.IntegerField(default=587, help_text='غالباً 465 لـ SSL أو 587 لـ TLS', verbose_name='بورت البريد (Port)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name='استخدام SSL (للبورت 465)'),
        ),
    ]
