# Generated by Django 6.1 on 2026-08-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omarusaapp', '0010_sitesetting_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_link',
            field=models.CharField(blank=True, default='About', max_length=50, verbose_name='نص رابط من نحن'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_email_placeholder',
            field=models.CharField(blank=True, default='البريد الإلكتروني', max_length=50, verbose_name='نص placeholder البريد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_follow',
            field=models.CharField(blank=True, default='FOLLOW', max_length=50, verbose_name='عنوان قسم المتابعة'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_get_in_touch',
            field=models.CharField(blank=True, default='GET IN TOUCH', max_length=50, verbose_name='عنوان قسم التواصل'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_message_placeholder',
            field=models.CharField(blank=True, default='الرسالة', max_length=50, verbose_name='نص placeholder الرسالة'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_name_placeholder',
            field=models.CharField(blank=True, default='الاسم', max_length=50, verbose_name='نص placeholder الاسم'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_send_message',
            field=models.CharField(blank=True, default='SEND MESSAGE', max_length=50, verbose_name='عنوان نموذج الرسالة'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_submit_btn',
            field=models.CharField(blank=True, default='إرسال', max_length=50, verbose_name='نص زر الإرسال'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_success_msg',
            field=models.CharField(blank=True, default='✅ تم إرسال رسالتك بنجاح! سنتواصل معك قريباً.', max_length=200, verbose_name='رسالة النجاح'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_link',
            field=models.CharField(blank=True, default='Home', max_length=50, verbose_name='نص رابط الرئيسية'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='menu_title',
            field=models.CharField(blank=True, default='Menu', max_length=50, verbose_name='عنوان القائمة'),
        ),
    ]
